#ifndef SUSAMUNE_MEM2_MAP_H
#define SUSAMUNE_MEM2_MAP_H

// Shared Wii MEM2 layout for the PPC loader/mod and the ARM Nintendont kernel.
// ARM uses physical 0x1xxxxxxx addresses; PPC cached aliases add 0x80000000.
// Keep this file C-compatible: it is included by all three build toolchains.

// ISO images and real discs are mutually exclusive, so both readers share the
// first 3 MiB. RealDI divides it into front/drive/tail-cache subranges.
#define NIN_MEM2_DISC_CACHE_PHYS_BASE         0x11000000u
#define NIN_MEM2_DISC_CACHE_PPC_BASE          0x91000000u
#define NIN_MEM2_DISC_CACHE_SIZE              0x00300000u

// Nintendont buffers relocated below the savestate window.
#define NIN_MEM2_SEGABOOT_PHYS_BASE          0x11300000u
#define NIN_MEM2_SEGABOOT_PPC_BASE           0x91300000u
#define NIN_MEM2_SEGABOOT_SIZE               0x00100000u

#define NIN_MEM2_DIMM_PHYS_BASE              0x11400000u
#define NIN_MEM2_DIMM_PPC_BASE               0x91400000u
#define NIN_MEM2_DIMM_SIZE                   0x00300000u

#define NIN_MEM2_DI_SCRATCH_PHYS_BASE        0x11700000u
#define NIN_MEM2_DI_SCRATCH_PPC_BASE         0x91700000u
#define NIN_MEM2_DI_SCRATCH_SIZE             0x00080000u

// Used only by the PPC loader before control passes to the game/kernel.
#define NIN_MEM2_LOADER_DISC_PHYS_BASE       0x11780000u
#define NIN_MEM2_LOADER_DISC_PPC_BASE        0x91780000u
#define NIN_MEM2_LOADER_DISC_SIZE            0x00180000u

// patch.bin / patch.txt handoff: the loader writes through the cached PPC
// alias and the ARM kernel consumes the same bytes through the physical alias.
#define NIN_MEM2_FILE_PATCH_PHYS_BASE        0x11900000u
#define NIN_MEM2_FILE_PATCH_PPC_BASE         0x91900000u
#define NIN_MEM2_FILE_PATCH_SIZE             0x005DF000u

// mod_<region>.bin staging (struct SusamuneModHeader, mod_bin.h). The PPC
// loader reads the file for the detected disc here before booting the kernel;
// PatchSusamune() copies the code out into MEM1 and nothing reads it again, so
// the mod is resident in exactly one place for the rest of the session.
//
// It shares the file-patch buffer's lifetime -- both are loader-to-kernel
// handoffs consumed at PatchGame time -- so it is carved off that buffer's tail
// rather than given memory of its own: 132 KiB out of six MiB, and the game
// never ships a patch.bin anyway. Deliberately NOT taken out of the snapshot
// window, whose payload can legitimately grow to fill its reservation.
#define SUSAMUNE_MEM2_MODBIN_PHYS_BASE       0x11EDF000u
#define SUSAMUNE_MEM2_MODBIN_PPC_BASE        0x91EDF000u
#define SUSAMUNE_MEM2_MODBIN_SIZE            0x00021000u

// Dedicated Susamune snapshot window. No Nintendont buffer may overlap this
// range. Its exclusive end is the settings block below.
#define SUSAMUNE_MEM2_SNAPSHOT_PHYS_BASE     0x11F00000u
#define SUSAMUNE_MEM2_SNAPSHOT_PPC_BASE      0x91F00000u
#define SUSAMUNE_MEM2_SNAPSHOT_SIZE          0x00FF0000u

// Dolphin exposes a separate 16 MiB aperture for the snapshot. Keep its final
// 64 KiB outside the snapshot payload for live emulator-only state; unlike the
// Wii addresses below, nothing on the ARM side consumes these bytes.
#define SUSAMUNE_DOLPHIN_SNAPSHOT_PPC_BASE   0x70000000u
#define SUSAMUNE_DOLPHIN_RUNTIME_PPC_BASE    0x70FF0000u
#define SUSAMUNE_DOLPHIN_RUNTIME_SIZE        0x00010000u
#define SUSAMUNE_DOLPHIN_PERSIST_PPC_BASE    0x70FF0000u
#define SUSAMUNE_DOLPHIN_PERSIST_SIZE        0x00001800u
#define SUSAMUNE_DOLPHIN_RECORDS_PPC_BASE    0x70FF1800u
#define SUSAMUNE_DOLPHIN_METADATA_PPC_BASE   0x70FF2000u
#define SUSAMUNE_DOLPHIN_CREATION_PPC_BASE   0x70FF2800u
#define SUSAMUNE_DOLPHIN_REGIONAL_PPC_BASE   0x70FF2D00u
#define SUSAMUNE_DOLPHIN_MENU_PPC_BASE       0x70FF2F00u
#define SUSAMUNE_DOLPHIN_CONFIG_PPC_BASE     0x70FF3300u
#define SUSAMUNE_DOLPHIN_FEATURE_PPC_BASE    0x70FF3500u
#define SUSAMUNE_DOLPHIN_ILING_PPC_BASE      0x70FF3600u
#define SUSAMUNE_DOLPHIN_PB_LIVE_PPC_BASE    0x70FFF800u
#define SUSAMUNE_DOLPHIN_PB_LIVE_SIZE        0x00000800u

// Settings/PB handoff block (struct SusamuneCfg, susamune_cfg.h). The ARM
// kernel fills it before boot and services the mod's independent ini and PB
// save doorbells. Carved off the top of the snapshot window rather than from
// Nintendont's buffers, since the snapshot's 16 MiB reservation is far larger
// than its use. Deliberately outside the snapshot payload so a savestate load
// does not rewind persistent data.
#define SUSAMUNE_MEM2_CFG_PHYS_BASE          0x12EF0000u
#define SUSAMUNE_MEM2_CFG_PPC_BASE           0x92EF0000u
#define SUSAMUNE_MEM2_CFG_SIZE               0x00010000u

// Runtime-only PPC state lives after the progress mailbox and before the live
// PB mirror. The ARM kernel never reads these windows.
#define SUSAMUNE_CONSOLE_RECORDS_PPC_BASE    0x92EF2400u
#define SUSAMUNE_CONSOLE_METADATA_PPC_BASE   0x92EF2C00u
#define SUSAMUNE_CONSOLE_CREATION_PPC_BASE   0x92EF3400u
#define SUSAMUNE_CONSOLE_REGIONAL_PPC_BASE   0x92EF3900u
#define SUSAMUNE_CONSOLE_MENU_PPC_BASE       0x92EF3B00u
#define SUSAMUNE_CONSOLE_CONFIG_PPC_BASE     0x92EF3F00u
#define SUSAMUNE_CONSOLE_FEATURE_PPC_BASE    0x92EF4100u
#define SUSAMUNE_CONSOLE_ILING_PPC_BASE      0x92EF4200u

#define SUSAMUNE_RECORDS_RUNTIME_SIZE         0x00000800u
#define SUSAMUNE_METADATA_RUNTIME_SIZE        0x00000800u
#define SUSAMUNE_CREATION_RUNTIME_SIZE        0x00000500u
#define SUSAMUNE_REGIONAL_RUNTIME_SIZE        0x00000200u
#define SUSAMUNE_MENU_RUNTIME_SIZE            0x00000400u
#define SUSAMUNE_CONFIG_RUNTIME_SIZE          0x00000200u
#define SUSAMUNE_FEATURE_RUNTIME_SIZE         0x00000100u
#define SUSAMUNE_ILING_RUNTIME_SIZE           0x00000100u

#define SUSAMUNE_CONFIG_SETTINGS_OFFSET       0x00000000u
#define SUSAMUNE_CONFIG_SETTINGS_SIZE         0x00000080u
#define SUSAMUNE_CONFIG_BINDS_OFFSET          0x00000080u
#define SUSAMUNE_CONFIG_BINDS_SIZE            0x00000040u
#define SUSAMUNE_CONFIG_INPUT_OFFSET          0x000000C0u
#define SUSAMUNE_CONFIG_INPUT_SIZE            0x000000A0u
#define SUSAMUNE_CONFIG_QFT_OFFSET            0x00000160u
#define SUSAMUNE_CONFIG_QFT_SIZE              0x00000080u
#define SUSAMUNE_CONFIG_ATTEMPTS_OFFSET       0x000001E0u
#define SUSAMUNE_CONFIG_ATTEMPTS_SIZE         0x00000020u

#if IS_EMULATOR
#define SUSAMUNE_MEM2_RECORDS_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_RECORDS_PPC_BASE
#define SUSAMUNE_MEM2_METADATA_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_METADATA_PPC_BASE
#define SUSAMUNE_MEM2_CREATION_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_CREATION_PPC_BASE
#define SUSAMUNE_MEM2_REGIONAL_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_REGIONAL_PPC_BASE
#define SUSAMUNE_MEM2_MENU_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_MENU_PPC_BASE
#define SUSAMUNE_MEM2_CONFIG_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_CONFIG_PPC_BASE
#define SUSAMUNE_MEM2_FEATURE_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_FEATURE_PPC_BASE
#define SUSAMUNE_MEM2_ILING_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_ILING_PPC_BASE
#else
#define SUSAMUNE_MEM2_RECORDS_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_RECORDS_PPC_BASE
#define SUSAMUNE_MEM2_METADATA_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_METADATA_PPC_BASE
#define SUSAMUNE_MEM2_CREATION_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_CREATION_PPC_BASE
#define SUSAMUNE_MEM2_REGIONAL_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_REGIONAL_PPC_BASE
#define SUSAMUNE_MEM2_MENU_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_MENU_PPC_BASE
#define SUSAMUNE_MEM2_CONFIG_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_CONFIG_PPC_BASE
#define SUSAMUNE_MEM2_FEATURE_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_FEATURE_PPC_BASE
#define SUSAMUNE_MEM2_ILING_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_ILING_PPC_BASE
#endif

#if SUSAMUNE_CONFIG_SETTINGS_OFFSET + SUSAMUNE_CONFIG_SETTINGS_SIZE > SUSAMUNE_CONFIG_BINDS_OFFSET || SUSAMUNE_CONFIG_BINDS_OFFSET + SUSAMUNE_CONFIG_BINDS_SIZE > SUSAMUNE_CONFIG_INPUT_OFFSET || SUSAMUNE_CONFIG_INPUT_OFFSET + SUSAMUNE_CONFIG_INPUT_SIZE > SUSAMUNE_CONFIG_QFT_OFFSET || SUSAMUNE_CONFIG_QFT_OFFSET + SUSAMUNE_CONFIG_QFT_SIZE > SUSAMUNE_CONFIG_ATTEMPTS_OFFSET || SUSAMUNE_CONFIG_ATTEMPTS_OFFSET + SUSAMUNE_CONFIG_ATTEMPTS_SIZE > SUSAMUNE_CONFIG_RUNTIME_SIZE
#error "Susamune configuration runtime slots overlap"
#endif

// PPC-only live PB profiles. The ARM doorbell payload remains immutable while
// a save is in flight; later PB changes queue here for the next write.
#define SUSAMUNE_MEM2_PB_LIVE_PPC_BASE       0x92EFF800u
#define SUSAMUNE_MEM2_PB_LIVE_SIZE           0x00000800u

#define NIN_MEM2_KERNEL_PHYS_BASE            0x12F00000u
#define NIN_MEM2_KERNEL_PPC_BASE             0x92F00000u

// Compile-time adjacency checks. Besides documenting the intended ownership,
// these prevent a future size/address edit from silently entering the snapshot.
#if NIN_MEM2_DISC_CACHE_PHYS_BASE + NIN_MEM2_DISC_CACHE_SIZE != NIN_MEM2_SEGABOOT_PHYS_BASE
#error "MEM2 map gap/overlap between disc cache and SegaBoot"
#endif
#if NIN_MEM2_SEGABOOT_PHYS_BASE + NIN_MEM2_SEGABOOT_SIZE != NIN_MEM2_DIMM_PHYS_BASE
#error "MEM2 map gap/overlap between SegaBoot and DIMM buffers"
#endif
#if NIN_MEM2_DIMM_PHYS_BASE + NIN_MEM2_DIMM_SIZE != NIN_MEM2_DI_SCRATCH_PHYS_BASE
#error "MEM2 map gap/overlap between DIMM and DI scratch buffers"
#endif
#if NIN_MEM2_DI_SCRATCH_PPC_BASE + NIN_MEM2_DI_SCRATCH_SIZE != NIN_MEM2_LOADER_DISC_PPC_BASE
#error "MEM2 map gap/overlap before the loader disc buffer"
#endif
#if NIN_MEM2_LOADER_DISC_PPC_BASE + NIN_MEM2_LOADER_DISC_SIZE != NIN_MEM2_FILE_PATCH_PPC_BASE
#error "MEM2 map gap/overlap before the file-patch buffer"
#endif
#if NIN_MEM2_FILE_PATCH_PHYS_BASE + NIN_MEM2_FILE_PATCH_SIZE != SUSAMUNE_MEM2_MODBIN_PHYS_BASE
#error "MEM2 file-patch buffer must end at the mod-blob staging area"
#endif
#if SUSAMUNE_MEM2_MODBIN_PHYS_BASE + SUSAMUNE_MEM2_MODBIN_SIZE != SUSAMUNE_MEM2_SNAPSHOT_PHYS_BASE
#error "MEM2 mod-blob staging area must end at the snapshot window"
#endif
#if SUSAMUNE_MEM2_SNAPSHOT_PHYS_BASE + SUSAMUNE_MEM2_SNAPSHOT_SIZE != SUSAMUNE_MEM2_CFG_PHYS_BASE
#error "MEM2 snapshot window must end at the settings block"
#endif
#if SUSAMUNE_MEM2_CFG_PHYS_BASE + SUSAMUNE_MEM2_CFG_SIZE != NIN_MEM2_KERNEL_PHYS_BASE
#error "MEM2 settings block must end at the Nintendont kernel"
#endif
#if SUSAMUNE_MEM2_PB_LIVE_PPC_BASE + SUSAMUNE_MEM2_PB_LIVE_SIZE != NIN_MEM2_KERNEL_PPC_BASE
#error "MEM2 live PB mirror must end at the Nintendont kernel"
#endif
#if SUSAMUNE_DOLPHIN_SNAPSHOT_PPC_BASE + SUSAMUNE_MEM2_SNAPSHOT_SIZE != SUSAMUNE_DOLPHIN_RUNTIME_PPC_BASE
#error "Dolphin runtime state must follow the snapshot window"
#endif
#if SUSAMUNE_DOLPHIN_RUNTIME_PPC_BASE + SUSAMUNE_DOLPHIN_RUNTIME_SIZE != 0x71000000u
#error "Dolphin runtime state must stay inside its 16 MiB aperture"
#endif
#if SUSAMUNE_DOLPHIN_PERSIST_PPC_BASE < SUSAMUNE_DOLPHIN_RUNTIME_PPC_BASE || SUSAMUNE_DOLPHIN_PERSIST_PPC_BASE + SUSAMUNE_DOLPHIN_PERSIST_SIZE > SUSAMUNE_DOLPHIN_PB_LIVE_PPC_BASE
#error "Dolphin persistence state overlaps another MEM2 window"
#endif
#if SUSAMUNE_DOLPHIN_PERSIST_PPC_BASE + SUSAMUNE_DOLPHIN_PERSIST_SIZE > SUSAMUNE_DOLPHIN_RECORDS_PPC_BASE || SUSAMUNE_DOLPHIN_RECORDS_PPC_BASE + SUSAMUNE_RECORDS_RUNTIME_SIZE > SUSAMUNE_DOLPHIN_METADATA_PPC_BASE || SUSAMUNE_DOLPHIN_METADATA_PPC_BASE + SUSAMUNE_METADATA_RUNTIME_SIZE > SUSAMUNE_DOLPHIN_CREATION_PPC_BASE || SUSAMUNE_DOLPHIN_CREATION_PPC_BASE + SUSAMUNE_CREATION_RUNTIME_SIZE > SUSAMUNE_DOLPHIN_REGIONAL_PPC_BASE || SUSAMUNE_DOLPHIN_REGIONAL_PPC_BASE + SUSAMUNE_REGIONAL_RUNTIME_SIZE > SUSAMUNE_DOLPHIN_MENU_PPC_BASE || SUSAMUNE_DOLPHIN_MENU_PPC_BASE + SUSAMUNE_MENU_RUNTIME_SIZE > SUSAMUNE_DOLPHIN_CONFIG_PPC_BASE || SUSAMUNE_DOLPHIN_CONFIG_PPC_BASE + SUSAMUNE_CONFIG_RUNTIME_SIZE > SUSAMUNE_DOLPHIN_FEATURE_PPC_BASE || SUSAMUNE_DOLPHIN_FEATURE_PPC_BASE + SUSAMUNE_FEATURE_RUNTIME_SIZE > SUSAMUNE_DOLPHIN_ILING_PPC_BASE || SUSAMUNE_DOLPHIN_ILING_PPC_BASE + SUSAMUNE_ILING_RUNTIME_SIZE > SUSAMUNE_DOLPHIN_PB_LIVE_PPC_BASE
#error "Dolphin Susamune runtime windows overlap"
#endif
#if SUSAMUNE_CONSOLE_RECORDS_PPC_BASE + SUSAMUNE_RECORDS_RUNTIME_SIZE > SUSAMUNE_CONSOLE_METADATA_PPC_BASE || SUSAMUNE_CONSOLE_METADATA_PPC_BASE + SUSAMUNE_METADATA_RUNTIME_SIZE > SUSAMUNE_CONSOLE_CREATION_PPC_BASE || SUSAMUNE_CONSOLE_CREATION_PPC_BASE + SUSAMUNE_CREATION_RUNTIME_SIZE > SUSAMUNE_CONSOLE_REGIONAL_PPC_BASE || SUSAMUNE_CONSOLE_REGIONAL_PPC_BASE + SUSAMUNE_REGIONAL_RUNTIME_SIZE > SUSAMUNE_CONSOLE_MENU_PPC_BASE || SUSAMUNE_CONSOLE_MENU_PPC_BASE + SUSAMUNE_MENU_RUNTIME_SIZE > SUSAMUNE_CONSOLE_CONFIG_PPC_BASE || SUSAMUNE_CONSOLE_CONFIG_PPC_BASE + SUSAMUNE_CONFIG_RUNTIME_SIZE > SUSAMUNE_CONSOLE_FEATURE_PPC_BASE || SUSAMUNE_CONSOLE_FEATURE_PPC_BASE + SUSAMUNE_FEATURE_RUNTIME_SIZE > SUSAMUNE_CONSOLE_ILING_PPC_BASE || SUSAMUNE_CONSOLE_ILING_PPC_BASE + SUSAMUNE_ILING_RUNTIME_SIZE > SUSAMUNE_MEM2_PB_LIVE_PPC_BASE
#error "console Susamune runtime windows overlap"
#endif
#if SUSAMUNE_DOLPHIN_PB_LIVE_PPC_BASE + SUSAMUNE_DOLPHIN_PB_LIVE_SIZE > SUSAMUNE_DOLPHIN_RUNTIME_PPC_BASE + SUSAMUNE_DOLPHIN_RUNTIME_SIZE
#error "Dolphin live PB mirror exceeds its MEM2 window"
#endif
#if (SUSAMUNE_DOLPHIN_PERSIST_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_RECORDS_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_METADATA_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_CREATION_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_REGIONAL_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_MENU_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_CONFIG_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_FEATURE_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_ILING_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_PB_LIVE_PPC_BASE & 31u) != 0
#error "Dolphin runtime-state windows must be cache-line aligned"
#endif
#if (SUSAMUNE_CONSOLE_RECORDS_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_METADATA_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_CREATION_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_REGIONAL_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_MENU_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_CONFIG_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_FEATURE_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_ILING_PPC_BASE & 31u) != 0
#error "console runtime-state windows must be cache-line aligned"
#endif

// Physical-to-PPC cached alias checks.
#if NIN_MEM2_DISC_CACHE_PHYS_BASE + 0x80000000u != NIN_MEM2_DISC_CACHE_PPC_BASE
#error "Invalid disc-cache PPC alias"
#endif
#if NIN_MEM2_SEGABOOT_PHYS_BASE + 0x80000000u != NIN_MEM2_SEGABOOT_PPC_BASE
#error "Invalid SegaBoot PPC alias"
#endif
#if NIN_MEM2_DIMM_PHYS_BASE + 0x80000000u != NIN_MEM2_DIMM_PPC_BASE
#error "Invalid DIMM PPC alias"
#endif
#if NIN_MEM2_DI_SCRATCH_PHYS_BASE + 0x80000000u != NIN_MEM2_DI_SCRATCH_PPC_BASE
#error "Invalid DI-scratch PPC alias"
#endif
#if NIN_MEM2_LOADER_DISC_PHYS_BASE + 0x80000000u != NIN_MEM2_LOADER_DISC_PPC_BASE
#error "Invalid loader-disc PPC alias"
#endif
#if NIN_MEM2_FILE_PATCH_PHYS_BASE + 0x80000000u != NIN_MEM2_FILE_PATCH_PPC_BASE
#error "Invalid file-patch PPC alias"
#endif
#if SUSAMUNE_MEM2_SNAPSHOT_PHYS_BASE + 0x80000000u != SUSAMUNE_MEM2_SNAPSHOT_PPC_BASE
#error "Invalid snapshot PPC alias"
#endif
#if SUSAMUNE_MEM2_MODBIN_PHYS_BASE + 0x80000000u != SUSAMUNE_MEM2_MODBIN_PPC_BASE
#error "Invalid mod-blob PPC alias"
#endif
#if SUSAMUNE_MEM2_CFG_PHYS_BASE + 0x80000000u != SUSAMUNE_MEM2_CFG_PPC_BASE
#error "Invalid settings-block PPC alias"
#endif
#if NIN_MEM2_KERNEL_PHYS_BASE + 0x80000000u != NIN_MEM2_KERNEL_PPC_BASE
#error "Invalid kernel PPC alias"
#endif

#endif // SUSAMUNE_MEM2_MAP_H
