# TODO: externalizing was a huge mistake... variant dirs are fucking stupid... integrate it back into one file and manage the build directory all yourself

Import('env')
Import('patch_dol')

source_files = Glob('src/*.c') + Glob('src/*.cpp')
mod_objs = env.Object(source_files)

obj_link_env = env.Clone(LINKFLAGS = env['LINKFLAGS'] + ['-r'])
mod_obj = obj_link_env.Program(target="#build/susamune.o", source=mod_objs) # TODO not using BUILD_DIR

in_dol_path = '#main.dol'
patched_dol = env.Command(
    target='#main.out.dol',
    source=[in_dol_path, "#build/susamune.o"],
    action=patch_dol
)
Return('patched_dol')