import argparse
import json
import os
import shutil
import sys
import zipfile
import subprocess
from pathlib import Path


def short_path(path):
    # Windows 8.3 short path (no spaces/parens), for feeding paths through sh.
    import ctypes
    buf = ctypes.create_unicode_buffer(512)
    if ctypes.windll.kernel32.GetShortPathNameW(str(path), buf, len(buf)):
        return buf.value
    return str(path)


def find_git_bash():
    # TEMPORARY: the vendored Nintendont Makefiles are written for a POSIX shell
    # (recipes use sed/tr/cp/[ ...), so on Windows the build must run through
    # Git for Windows' bundled sh + coreutils. This whole detour disappears once
    # the launcher build is ported to CMake.
    roots = []
    git = shutil.which("git")
    if git:
        roots.append(Path(git).parent.parent)
    roots += [
        Path(r"C:\Program Files\Git"),
        Path(r"C:\Program Files (x86)\Git"),
        Path(os.path.expandvars(r"%LOCALAPPDATA%\Programs\Git")),
    ]
    for root in roots:
        sh = root / "usr" / "bin" / "sh.exe"
        if sh.exists():
            return sh
    raise RuntimeError("Could not locate Git Bash (its sh + coreutils are needed to run the Nintendont Makefiles).")

LAUNCHER_DIR = Path(__file__).resolve().parent.parent / "launcher"
BUILTIN_TOOLCHAIN_DIR = LAUNCHER_DIR / "nintendont_devkitpro"
BUILTIN_TOOLCHAIN_ZIP = LAUNCHER_DIR / "nintendont_devkitpro_win32.zip"
DEVKITPPC = Path(os.environ.get("DEVKITPPC", BUILTIN_TOOLCHAIN_DIR / "devkitPPC")).resolve()
DEVKITARM = Path(os.environ.get("DEVKITARM", BUILTIN_TOOLCHAIN_DIR / "devkitARM")).resolve()

NEED_TOOLCHAIN_UNZIP = ((not os.path.exists(BUILTIN_TOOLCHAIN_DIR)) and
    ((os.environ.get("DEVKITPPC") is None) or (os.environ.get("DEVKITARM") is None)))


# HBC app folder produced by the loader build (boot.dol lands here).
APP_DIR = LAUNCHER_DIR / "nintendont"
APP_NAME = "susamune_launcher"
META_TEMPLATE = LAUNCHER_DIR / "meta.xml.j2"
APP_ICON = LAUNCHER_DIR / "icon_jp.png"

SCRIPTS_DIR = Path(__file__).resolve().parent


def ensure_compiler_dlls():
    # cc1/cc1plus live under libexec/ and need the mingw runtime DLLs (e.g.
    # libwinpthread-1.dll) that ship next to the gcc driver in bin/. Windows
    # searches an exe's own directory first, so mirror the bin/ DLLs beside each
    # cc1 rather than relying on them being on PATH.
    for dk in (DEVKITARM, DEVKITPPC):
        dlls = list((dk / "bin").glob("*.dll"))
        for cc1 in dk.rglob("cc1*.exe"):
            for dll in dlls:
                dest = cc1.parent / dll.name
                if not dest.exists():
                    shutil.copyfile(dll, dest)


def install_shims():
    # The bundled toolchain lacks devkitPro's bin2s and elf2dol, which wii_rules
    # relies on (bin2o for data/ files, and the %.dol rule). Drop shims onto the
    # toolchain bin dir (which is on the recipe PATH) that forward to our Python
    # implementations.
    python = Path(sys.executable).as_posix()
    for tool in ("bin2s", "elf2dol"):
        wrapper = DEVKITPPC / "bin" / tool
        impl = (SCRIPTS_DIR / f"{tool}.py").as_posix()
        wrapper.write_text(f'#!/bin/sh\nexec "{python}" "{impl}" "$@"\n')
        os.chmod(wrapper, 0o755)


def write_inject_header(manifest, path):
    code = bytes.fromhex(manifest["code"])
    lines = [
        "// Generated by build_launcher.py from the mod manifest. Do not edit.",
        "#ifndef SUSAMUNE_INJECT_H",
        "#define SUSAMUNE_INJECT_H",
        "",
        f"#define SUSAMUNE_GAME_ID 0x{manifest['game_id']:08X}u",
        f"#define SUSAMUNE_CODE_BASE 0x{manifest['base_addr']:08X}u",
        f"#define SUSAMUNE_CODE_SIZE {len(code)}u",
        f"#define SUSAMUNE_WRITE_COUNT {len(manifest['writes'])}u",
        f"#define SUSAMUNE_ARENA_RESERVE 0x{manifest.get('region_reserve', 0x8000):X}u",
        "",
        "static const unsigned char susamune_code[] = {",
    ]
    for i in range(0, len(code), 12):
        lines.append("\t" + "".join(f"0x{b:02X}," for b in code[i:i + 12]))
    lines += [
        "};",
        "",
        "static const struct { unsigned int addr; unsigned int val; } susamune_writes[] = {",
    ]
    for addr, val in manifest["writes"]:
        lines.append(f"\t{{0x{addr:08X}u, 0x{val:08X}u}},")
    lines += ["};", "", "#endif", ""]
    path.write_text("\n".join(lines))


def render_meta(manifest, source):
    import jinja2
    try:
        version = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=str(LAUNCHER_DIR.parent), text=True).strip()
    except Exception:
        version = "unknown"
    template = jinja2.Template(META_TEMPLATE.read_text())
    return template.render(
        region=manifest["region"],
        version=version,
        disc_name=manifest["disc_name"],
        source=source
    )


def make_zip(out_zip, meta_xml):
    with zipfile.ZipFile(out_zip, "w", zipfile.ZIP_DEFLATED) as z:
        z.write(APP_DIR / "boot.dol", f"{APP_NAME}/boot.dol")
        z.write(APP_ICON, f"{APP_NAME}/icon.png")
        z.writestr(f"{APP_NAME}/meta.xml", meta_xml)


def main():
    ap = argparse.ArgumentParser(description="Build the custom Nintendont launcher with the mod injected.")
    ap.add_argument("--source", default="di", choices=["di", "sd", "usb"])
    ap.add_argument("--manifest", required=True, help="Mod manifest JSON from link_mod.py launcher")
    ap.add_argument("--out-zip", required=True, help="Output HBC app zip")
    args = ap.parse_args()

    if NEED_TOOLCHAIN_UNZIP:
        with zipfile.ZipFile(BUILTIN_TOOLCHAIN_ZIP, "r") as z:
            z.extractall(LAUNCHER_DIR)

    manifest = json.loads(Path(args.manifest).read_text())
    # The generated inject header is a build artifact (its contents depend on the
    # mod blob + build flags), so it lives in the build dir alongside the
    # manifest, not in version control. The kernel Makefile picks it up via
    # -I$(SUSAMUNE_INJECT_DIR) below.
    inject_dir = Path(args.manifest).resolve().parent
    write_inject_header(manifest, inject_dir / "susamune_inject.h")
    install_shims()
    ensure_compiler_dlls()
    APP_DIR.mkdir(parents=True, exist_ok=True)  # loader copies boot.dol here

    env = dict(
        os.environ,
        DEVKITPRO=str(DEVKITPPC.parent),
        DEVKITPPC=str(DEVKITPPC),
        DEVKITARM=str(DEVKITARM),
    )

    # Command-line make variable (propagates to the recursive kernel make) that
    # points the compiler's include search at the build dir where we just wrote
    # susamune_inject.h. Forward slashes so it's happy through sh and gcc.
    inject_inc = f"SUSAMUNE_INJECT_DIR={inject_dir.as_posix()}"

    make = shutil.which("make")
    if make is None:
        raise RuntimeError("`make` not found on PATH")
    cmd = [make, "-C", str(LAUNCHER_DIR), inject_inc]
    if os.name == "nt":
        # Drive make through Git Bash's sh + coreutils (see find_git_bash) so the
        # build works from any parent shell. Recursive `$(MAKE)` also runs
        # through sh, which chokes on spaces/parens in the make path (e.g.
        # "Program Files (x86)"), so feed sub-makes the 8.3 short path and select
        # the bundled Windows zip.
        sh = find_git_bash()
        env["PATH"] = str(sh.parent) + os.pathsep + env["PATH"]
        make_short = short_path(make)
        cmd = [make_short, "-C", str(LAUNCHER_DIR),
               f"MAKE={make_short}", f"SHELL={short_path(sh)}", "windows=1",
               inject_inc]

    subprocess.run(cmd, env=env, check=True)

    make_zip(Path(args.out_zip), render_meta(manifest, args.source))


if __name__ == "__main__":
    main()
