"""Generate susamune_inject.h from the mod manifest produced by
`link_mod.py launcher`.

The header carries the mod code blob and the (addr, word) write list that the
Nintendont kernel (launcher/kernel/Patch.c, under __has_include) applies to
MEM1 at boot. It is a build artifact: its contents depend on the mod blob and
build flags, so it lives in the build dir and is a first-class CMake dependency
of the kernel (a mod-source change regenerates it and relinks only the kernel).

Usage: gen_inject_header.py MANIFEST.json -o susamune_inject.h
"""
import argparse
import json
import sys
from pathlib import Path


def write_inject_header(manifest, path):
    code = bytes.fromhex(manifest["code"])
    lines = [
        "// Generated by gen_inject_header.py from the mod manifest. Do not edit.",
        "#ifndef SUSAMUNE_INJECT_H",
        "#define SUSAMUNE_INJECT_H",
        "",
        f"#define SUSAMUNE_GAME_ID 0x{manifest['game_id']:08X}u",
        f"#define SUSAMUNE_CODE_BASE 0x{manifest['base_addr']:08X}u",
        f"#define SUSAMUNE_CODE_SIZE {len(code)}u",
        f"#define SUSAMUNE_WRITE_COUNT {len(manifest['writes'])}u",
        f"#define SUSAMUNE_ARENA_RESERVE 0x{manifest.get('region_reserve', 0x8000):X}u",
        "",
        "static const unsigned char susamune_code[] = {",
    ]
    for i in range(0, len(code), 12):
        lines.append("\t" + "".join(f"0x{b:02X}," for b in code[i:i + 12]))
    lines += [
        "};",
        "",
        "static const struct { unsigned int addr; unsigned int val; } susamune_writes[] = {",
    ]
    for addr, val in manifest["writes"]:
        lines.append(f"\t{{0x{addr:08X}u, 0x{val:08X}u}},")
    lines += ["};", "", "#endif", ""]
    Path(path).write_text("\n".join(lines))


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("manifest", help="Mod manifest JSON from link_mod.py launcher")
    ap.add_argument("-o", "--output", required=True)
    args = ap.parse_args(argv)

    manifest = json.loads(Path(args.manifest).read_text())
    write_inject_header(manifest, args.output)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
